### ISSUE TITLE
Security settings not working consistantly - missing "0" on login sceen

### ISSUE THREAD

**Issue by roru69** [daper/nextcloud-passwords-app#11]
Hi,

First of all I use a Samsung Galaxy S7 edge on stock Oreo (8).

I have been using this app for a couple of weeks now and was happy to see that there was a loginscreen implemented. I have tested this a couple of days, but there are a few issues that need to be addressed.

When I set a code, and don't set a timeout, close the app, the login screen doesn't pop up when I start the app. the passwords are visible without logging in most of the time, in some cases the password screen pops up, most of the time I can see the passwords without logging in. Setting a timeout doesn't seem to have any effect.

The login screen is missing a "0" only the numerals "1" to "9" are displayed, so setting a password with a "0" results in not able to log in.

**Setting a code and leave the timeout disabled for me would mean:**

- Shift focus to another app should result in showing the login sceen.
- Turning of the phone screen, show login screen.
- Restarting the app, show login screen

.

**Setting a timeout would mean when the timeout is reached:**

- After timeout - Shift focus = Show login screen
- After timeout - turning of sceen = Show login sceen
- Stopping and restarting app - always show login sceen regardless of timeout.

If these issues are solved I think it is a great addition to the nextcloud password app.

Regards, Roru69

**Comment by daper** [comment]
Hi @roru69,

Thank you for taking your time on writing this issue, really appreciated. You made me laugh so loud when I realized the '0' wasn't there. I was planing on releasing the fix for the behavior when the app shuts down/quits; there was already a commit for that. I will now complete it with your suggestions. Thanks again.

**Comment by daper** [comment]
Latest changes published on v1.9. Closing.
