### ISSUE TITLE
Login into nextcloud website with this app not possible

### ISSUE THREAD

**Issue by chrbayer** [daper/nextcloud-passwords-app#12]
It is not possible to login to my nextcloud server with the password app: After inserting the URL "https://criby.de/nextcloud", the app shows "Network Error" for a short time and goes back to the screen from the beginning again, where I can insert the URL once again.

Same behaviour on Android 7.1, 8.1 and 9.0. My site uses a self signed certificate, but the CA root cert is added into Androids trusted CAs.

**Comment by chrbayer** [comment]
Thanks for the answer! I try to work on this, how do I have to build the app? I did "npm install" in root directory and than "./gradlew installDebug" in android subdirectory. This worked, but the resultung app throw an exception about missing assets in the apk... Do I have to use some kind of server for the assets (I guess the complete js stuff...)? And how does it work?

Thank you very much for your support!

**Comment by daper** [comment]
Hi! Thanks for your efforts on debugging. You are right. Eighter your run a single "react-native run-android" or if you want to see the js bundler logs you can run first "npm start" and then in a separate console the first command. Please feel free to post back your debugging conclusions, will be very appreciated.

**Comment by daper** [comment]
Latest release already available with these changes: v1.10.
