### ISSUE TITLE
Cant pull Sites

### ISSUE THREAD

**Issue by david883** [daper/nextcloud-passwords-app#13]
Hello, I have the app installed on Android 9. You can open it and I can specify the account and log in to my Nextcloud server. It appears a circle and under it is "pulling sites" but it does not happen. Even after several attempts and changing the access data, the app does not work as desired.

**Comment by daper** [comment]
Hi, sad to read this. But there is an open issue about this problem, have a look at #4. I could not replicate, help on debugging will be very appreciated.
