### ISSUE TITLE
Crashes when clicking on 'copy login' button from password list

### ISSUE THREAD

**Issue by Salokyn** [daper/nextcloud-passwords-app#15]
Version 1.10 Android (oneplus 3)
Nextcloud 15
Passwords 2019.01

Hi,
When I click on the 'copy login' button from passwords list, the app crashes quite often. 

It seems it only happens for logins containing only numbers.

**Comment by daper** [comment]
Hi @Salokyn, sorry for the late reply. But ain't found any problem with numbers-only passwords while coping. I will anyway try to reproduce it on a development environment, where you can see almost any error messages thrown. But if you can do the same and paste here the exact error, would be very helpful.

There is no development/debug documentation yet, sadly. But maybe you can find some light on this comment: https://github.com/daper/nextcloud-passwords-app/issues/12#issuecomment-449773585.  Anyway I could advise you with any trouble you can find running a development version. Just drop here whatever blocks you :)

**Comment by Salokyn** [comment]
I don't know how to do all this.

But if it helps, when I have a numerical login that begins with 0's in passwords nextcloud app, the heading 0's don't appear in the android app. I think that numerical values are not kept as strings.

**Comment by daper** [comment]
@Salokyn Thanks! that was the best example. I found the issue... And you were right, numeric passwords are treated as numbers therefore leading 0s are removed. I hope I can make a release by the end of the month. Thank you again this was a tricky to find bug.

**Comment by Salokyn** [comment]
👍

**Comment by daper** [comment]
Hi @Salokyn, release v1.11 is already rolled out. You will need to reinstall manually the app, or clear its storage as migrations for the sqlite database are not programmed. If you find any trouble let me know.

**Comment by Salokyn** [comment]
Hi @daper,
I updated from google play and cleared the app storage.

OK for passwords. Heading zeroes are well treated.
FAIL for logins. The app crashesd on copy and heading zeroes disappear.

--> Logins seem not to be treated has strings.

**Comment by daper** [comment]
@Salokyn, I cannot believe it... I will fix and release again as soon as possible.

**Comment by Salokyn** [comment]
Hi,
Any chance to release a new version soon ?

**Comment by xsus95** [comment]
Still same problem with usernames like '442693'

**Comment by daper** [comment]
Released on v1.13.

**Comment by Salokyn** [comment]
Works for me 👍
