### ISSUE TITLE
F-droid build

### ISSUE THREAD

**Issue by mmalisz** [daper/nextcloud-passwords-app#16]
Would it be possible to add the application to f-droid repository?

**Comment by daper** [comment]
If it's free I don't see any reason to not do it. I'll have a look at it.

**Comment by violoncelloCH** [comment]
It's free... 
just take a look here:
https://f-droid.org/en/docs/FAQ_-_App_Developers/

**Comment by mokman** [comment]
f-droid release would be great, for people without google services.

**Comment by Poussinou** [comment]
I opened a Request For Packaging here: https://gitlab.com/fdroid/rfp/issues/948

You're welcome to join the discussion:)

**Comment by daper** [comment]
Hi! I've did some scripts to complete an f-droid build, they are located under tools directory. But I need some help about how to proceed. Moreover how to sign the app with f-droid. @Poussinou ?

**Comment by daper** [comment]
Hi! Opening again due to latest version ([v1.11](https://github.com/daper/nextcloud-passwords-app/releases/tag/v1.11)) is not building. Reference [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/4852).

**Comment by Poussinou** [comment]
This version is now [available](https://f-droid.org/packages/com.nextcloudpasswords/), you can close this Issue :)
