### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by ezraholm50** [daper/nextcloud-passwords-app#19]
Hello!

I've recently switched from Android to iOS and i'd love to use this app. Near future perhaps?
Or any pointers to help get this started?

**Comment by daper** [comment]
Hi @ezraholm50, no there is no plan to publish on iOS as the developer account is $99 yearly. The first version of the app worked on iOS I don't know if nowadays it still will.

**Comment by ezraholm50** [comment]
I get it. Id be willing to pay, but you have to find the time... Thanks anyway!

Verstuurd vanaf mijn iPhone

**Comment by zippytiff** [comment]
Hi,

Is there a way to get in contact ?

I was messaging with marius-wieschollek (author from passwords main app) about getting this fired up again on iOS and my software team is willing to give it a go, albeit as a 'fun' project. We will be happy to fund the Apple Developer licence etc

Let me know

ZT

**Comment by daper** [comment]
Hi @zippytiff, sure, you can contact me directly by [mail](mailto:david@daper.email). It shouldn't be thought to fix the iOS part. As far as I remember it is only the fingerprint stuff, everything else should work. I have many things on my table right now, but I will be glad to work together to move this on.

**Comment by ezraholm50** [comment]
I’d be glad to help to test.

**Comment by zippytiff** [comment]
Brilliant, lets make this happen

ZT

**Comment by ezraholm50** [comment]
Hey guys any progress? Let me know what to do.

**Comment by marti28** [comment]
Just started using a selfhosted instance of nextcloud an really really like to have an iOS app. Any updates? If you need a tester, sign me up!

**Comment by zippytiff** [comment]
I have paid the Apple licence and sent details over to the fantastic chap who has got the code. I’ll drop him an email later

ZT

On 16 May 2019, at 12:20, marti28 <notifications@github.com<mailto:notifications@github.com>> wrote:


Just started using a selfhosted instance of nextcloud an really really like to have an iOS app. Any updates? If you need a tester, sign me up!

**Comment by mmnaseri** [comment]
@daper @zippytiff Thanks for the great work and the support. I'd be willing (as I suspect many users will be) to chip in and get this rolling :) I'd love to get all my passwords and other stuff into this app and get rid of the other password managers I use for my phone usage.

**Comment by daper** [comment]
Hi @mmnaseri, any kind of help is very appreciated as I cannot spend as much time as I would like here. @zippytiff sent me an invitation for an apple dev account but I couldn't accept it on time and it expired. Maybe you both could work together to bring it up for iOS. It should work as it does on android. Right now the android version has many issues to attend and I cannot put more things on my table. I would like to be in CC, because although sometimes it seems the opposite, I read all the emails. And thanks again guys.

**Comment by zippytiff** [comment]
Hi

Sorry I didn’t realise it had expired, I will resend

Regards

ZT

**Comment by marti28** [comment]
Any updates on this one? Is there something I can do (not a developer, but a happy user)?

**Comment by xlucero1** [comment]
@zippytiff & @daper  I am very excited to see this thread rolling. I would be happy and willing to pay for this and support anyway I can, testing or whatever. I love the team work

**Comment by JBM1866** [comment]
Would also be willing to pay for the developer account if it would assist in getting the iOS App published.

**Comment by zippytiff** [comment]
Hi

It’s all paid for and waiting for the next steps

Regards

Z

On 22 Sep 2019, at 06:59, JBM1866 <notifications@github.com> wrote:

﻿

Would also be willing to pay for the developer account if it would assist in getting the iOS App published.

**Comment by techman2005** [comment]
I would be willing to donate as well really looking forward to an iOS app. Let me know where I can do so.

**Comment by ammannbe** [comment]
Is there any plan who and how you'll create the app?
I'm currently working on some apps which are created with `ionic`, `anuglar` and `cordova`. With that we could use only one codebase for iOS and Android and I could help you to develop the app.
Would something be said against it? I think some native features wouldn't be available, but is it necessary?

**Comment by zippytiff** [comment]
Hi David,

Sorry for my not focusing on this too much, but id like to give this some attention and see it through to a published iOS app

I have just mailed you

Here's hoping we can get this last piece of the Nextcloud Passwords eco-system done ;-)

Regards

ZT

**Comment by gewgaw4u** [comment]
As an avid user of nextcloud passwords and newly switched over to iOS would love to see this happen. Would donate or pay for paid version of app.

**Comment by zippytiff** [comment]
I still have everything (paid for developer account) ready to go

Lets hope for a 2020 launch

Sent from my iPhone

On Dec 28, 2019, at 03:04, gewgaw4u <notifications@github.com> wrote:

﻿

As an avid user of nextcloud passwords and newly switched over to iOS would love to see this happen. Would donate or pay for paid version of app.

**Comment by trupf** [comment]
I would also very much like to have this app work with iOS

**Comment by daper** [comment]
I feel sorry but I no longer have a Mac to continue developing for iOS. So I have to close this as for the moment there is no chance to do it. Moreover I started to develop some native modules for Android for the SSO and auto complete features. So since now the iOS part might be broken or at least lack the support of those features. But anyways if anyone is interested and wants to make a PR. It will be very very welcomed. :disappointed:
