### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by bendikrb** [daper/nextcloud-passwords-app#21]
I am unable to get the app started, as it eventually just ends up back at the login screen after "successful login", "pulling sites" and "pulling folders"..

1) https://imgur.com/a/RNyAuCD
2) https://imgur.com/a/SsmJGPt

**Comment by daper** [comment]
Hi @bendikrb, which version of nextcloud, nextcloud passwords, android and android app are you using? There is an already open issue about this problem and I hope to fix it in the next release. Check out the issue #4. If you can post there your answer, it would be better, thanks.
