### ISSUE TITLE
Donate button may lead to banishment Form Play 

### ISSUE THREAD

**Issue by Debianer** [daper/nextcloud-passwords-app#23]
Recently there was a story in the German news about a popluar app for public transport in Germany that was removed from because the automatic scan detected a donation button. The author said that the donation button remains hidden when the app is installed via Play, but that didn't help. The button had to be removed entirely.

From that I learned that donation buttons apparently aren't allowed. From my understanding.

**Comment by Poussinou** [comment]
@Debianer Could you please provide a link to an article about this? I'm really interested here...

Thanks

**Comment by Debianer** [comment]
In German:

https://www.heise.de/newsticker/meldung/Nahverkehrs-App-Oeffi-ist-zurueck-im-Play-Store-4153880.html

> @Debianer Could you please provide a link to an article about this, even if it's in German? I'm really interested here...
> 
> Thanks

https://play.google.com/store/apps/details?id=de.schildbach.oeffi

The app is, by far, the most popular independent public transport app in Germany. It now supports lot of other countries, has more than five millions installs and goes back to 2010 or so.

The donate button was disabled and most likely part of the code (I think the developer mentioned this?), because he enables it for other repositories besides Google play.

**Comment by Poussinou** [comment]
Hum interesting. A lot of FLOSS Android apps have a donate button, even if they are on the Google Play Store, it's gonna be complicated for them if Google decide to aggressively remove them from the Store...

**Comment by morgankevinj** [comment]
Can you enable donation as an in app purchase so that you can be payed with google play credit?

**Comment by daper** [comment]
Closing this hoping that no one bans a fully open source, non profitable protect.
