### ISSUE TITLE
"Google Chrome for Android 71 - ONEPLUS A6000" in Nextcloud Sessions

### ISSUE THREAD

**Issue by notthebee** [daper/nextcloud-passwords-app#24]
Each time I access the app my Nextcloud instance detects it as "ONEPLUS A6000" for some reason, even though I don't own a OnePlus. Is this an intended behavior? The app version is 1.10.

![image](https://user-images.githubusercontent.com/30384331/55102386-8f557580-50c6-11e9-9412-a430c7d6ad38.png)

**Comment by daper** [comment]
Hi @notthebee,

That is not intended. It must have something cached when I compiled. But I already knew about it. Next version will have a change near [Login.js:178](https://github.com/daper/nextcloud-passwords-app/blob/7bdf91a084f08abaf37eea977cbe1facd112e318/src/Login.js#L178), that will include the User-Agent header to the login request which is what Nextcloud uses to name each session. It will be something like "Nextcloud Passwords for Android".
