### ISSUE TITLE
White page instead of details 

### ISSUE THREAD

**Issue by LaurentGui** [daper/nextcloud-passwords-app#33]
Hello when I click on a item, a white page appears instead of the details of the item.
best regards

**Comment by nsuchold** [comment]
The same issue here. I can copy the username and pass from overview page, but the details page show a blank screen.

**Comment by daper** [comment]
Hey! Thank you for taking your time on letting me know about this. As well many others reported the same, seems a problem introduced on the latest version. And it's the first thing to tackle on my to-do. You can manually download and install the previous version from this repo. As a temporary workaround until I find the time to trace and fix the bug. Sorry for the inconveniences.

**Comment by daper** [comment]
Hi! This looks like duplicated of #38.

**Comment by daper** [comment]
This could be related with #62. I could reproduce the behavior but confirmation would be helpful too.

**Comment by daper** [comment]
This should be fixed on the latest release. Feel free to reopen if needed.
