### ISSUE TITLE
App does not remember server address

### ISSUE THREAD

**Issue by punk-t** [daper/nextcloud-passwords-app#35]
Hello!

I think I need to re-open issue #20. Exactly the same behaviour here.

I already tried this logout thing. This solves the described app hang but I also need to enter my server address again.

I'm using Wieschollek's Password App ~~2019.6~~ (version 2019.7.1) on a own Nextcloud installation (version 15.0.7)

Any hints or is this behaviour by design?

Best wishes
Punkt

**Comment by daper** [comment]
Hi @punk-t, it should remember your address on the last version. I am closing this for the moment, but feel free to re-open if necessary.
