### ISSUE TITLE
Copy button do not exist for user or address

### ISSUE THREAD

**Issue by godfuture** [daper/nextcloud-passwords-app#37]
When I open a password, there are only buttons for passwords to view and copy its data. Other fields like user and address are missing.

**Comment by daper** [comment]
Hi @godfuture and sorry for not have addressed it before. But could you explain with screenshots maybe which are the buttons you are missing? I am closing the issue for now as it has passed a lot of time, but feel completely free to reopen.

**Comment by godfuture** [comment]
Copy button missing:
![image_2020-03-06_09-11-34](https://user-images.githubusercontent.com/4669278/76064894-d280bf80-5f8a-11ea-82b4-b539894734c2.jpg)

**Comment by daper** [comment]
Thank you for the clarification!

**Comment by daper** [comment]
Closing as it's released but feel free to reopen if needed.
