### ISSUE TITLE
App closes when trying to copy username

### ISSUE THREAD

**Issue by AllirionX** [daper/nextcloud-passwords-app#38]
With one of my password, I cannot copy the username as it closes the app.

Here is the cause of the crash:
07-09 21:52:41.457 I/tcloudpassword(28226): Background concurrent copying GC freed 157194(5MB) AllocSpace objects, 8(416KB) LOS objects, 49% free, 5MB/10MB, paused 80us total 103.294ms

**Comment by Salokyn** [comment]
Maybe that's related to #15 ?
Does the username contain only numbers ?

**Comment by AllirionX** [comment]
Yes, it looks like it, even though I cannot get the same crash cause to be printed in the logs anymore.

**Comment by godfuture** [comment]
Same here. App crashes when trying to copy a user name that holds only numbers.

**Comment by daper** [comment]
This looks like a duplicate of #15
