### ISSUE TITLE
the app stucks on "pulling sites"

### ISSUE THREAD

**Issue by NodokaMurmevent** [daper/nextcloud-passwords-app#4]
no error message on phone but on my nextcloud : 
```

Error | passwords | OCA\Passwords\Exception\ApiException: Internal Favicon API Error | 2018-12-01T14:27:36+0100
    /var/www/cloud.symphonie-of-code.fr/apps/passwords/lib/Controller/Api/ServiceApiController.php - line 180:

    OCA\Passwords\Services\FaviconService->getFavicon("secure.amiami.com", 32)

    /var/www/cloud.symphonie-of-code.fr/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("secure.amiami.com", 32)

    /var/www/cloud.symphonie-of-code.fr/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "getFavicon")

    /var/www/cloud.symphonie-of-code.fr/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "getFavicon")

    /var/www/cloud.symphonie-of-code.fr/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramew ... {}, { domain: "s ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ domain: "s ... "})

    /var/www/cloud.symphonie-of-code.fr/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { domain: "s ... "})

    /var/www/cloud.symphonie-of-code.fr/lib/base.php - line 987:

    OC\Route\Router->match("/apps/passw ... 2")

    /var/www/cloud.symphonie-of-code.fr/index.php - line 42:

    OC::handleRequest()

Error | passwords | Error: Call to undefined method Gmagick::setImageCompressionQuality() | 2018-12-01T14:27:36+0100
Error | passwords | Error: Call to undefined method Gmagick::setImageCompressionQuality() | 2018-12-01T14:27:36+0100
```

my server are config for use PHP DGlib

**Comment by NodokaMurmevent** [comment]
nextcloud 14.0.4
app from the app store installed today
Server : debian stretch, nginx & php7.2

password is config for use PHP GD : 
![screenshot](https://screenshotscdn.firefoxusercontent.com/images/80c2eb73-54de-4aa6-ba63-ee32160d2222.png)

Gmagick is mandatory for the app ?

**Comment by daper** [comment]
Not at all, GMagic is an extension of php it has nothing to do on the app.
I think you need to fix this error `Error: Call to undefined method
Gmagick::setImageCompressionQuality()` on the php side.

**Comment by NodokaMurmevent** [comment]
ok i have correct the error with a simple `apt install php-gmagick` but i am always stuck on pulling sites

**Comment by daper** [comment]
Hi @NodokaMurmevent, can you please try this curl command and say if you see any errors?

curl -u <YOUR NC USER>:<YOUR NC PASSWORD> -X GET 'https://<YOUR NC HOST>/index.php/apps/passwords/api/1.0/password/list' -H 'OCS-APIRequest: true' -d '{ detailLevel: "model+folder" }'

This is the same call the app uses while getting passwords data.

**Comment by NodokaMurmevent** [comment]
i try the command on my PC and it's work i have a json result of my account & passwords.

it's possible to dl the apk ? maybe a problem with the google play version

**Comment by daper** [comment]
Yes, the apk is [here](https://github.com/daper/nextcloud-passwords-app/releases) under the "Releases" tab. APK is the same there and on google play. It's weird anyway, if that works it should work also on the app. If you wish try to run the development version with android-tools and react. It works for me with nextcloud (14.0.3) and nextcloud passwords (2018.12.0)

**Comment by daper** [comment]
Which kind of https certificate are you using? Is it signed by one of the most common CAs (like LetsEncrypt)?

**Comment by jookk** [comment]
Le rsa and ec

**Comment by daper** [comment]
So ain't have idea then. Try to run the development version then as I said, sorry.

**Comment by redisded** [comment]
Hi again ;-)

Same here, curl command work from my computer.
If I may give a suggestion : a log of what happen on the phone would be nice.

Best regards.

Redisded.

**Comment by redisded** [comment]
Hi,

new information, only happen for me when I try to use an application token (I use totp on my nextcloud), if I log in with my regular password an then use my totp code, retriving passwords work fine.

Problem is when I log out, I cannot log in again without going in android parameters and clear cache and user data of the application.

I log out because I don't want the application to let my password always available without authentication, but I'll open a different issue for that ;-)

Best regards,

Redisded.

**Comment by mmalisz** [comment]
I can confirm, that it happens when using app tokens. Loging in with regular credentials doesn't break the app. I can also confirm, that after the app hangs on 'pulling sites' log out doesn't work at all (will get the 'pulling sites' message.

**Comment by daper** [comment]
Hi! Thank you both for pointing out the app tokens problem. I will investigate deeper, but it makes sense for me... Never tried that auth method. :/

**Comment by ThePatzen** [comment]
Hi!

Same issue here!

I'm useing the IMAP user backend! 

`{"reqId":"zIMSr5nIxfvhcNFyDrMR","level":2,"time":"2019-01-14T09:31:59+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/password\/list","message":"Login failed: 'd.egger%40e-mx.at' (Remote IP: '46.74.82.159')","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}
{"reqId":"zIMSr5nIxfvhcNFyDrMR","level":1,"time":"2019-01-14T09:31:59+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/password\/list","message":"Bruteforce attempt from \"46.74.82.159\" detected for action \"login\".","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}
{"reqId":"zIMSr5nIxfvhcNFyDrMR","level":2,"time":"2019-01-14T09:32:05+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/password\/list","message":"Login failed: 'd.egger%40e-mx.at' (Remote IP: '46.74.82.159')","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}
{"reqId":"zIMSr5nIxfvhcNFyDrMR","level":1,"time":"2019-01-14T09:32:05+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/password\/list","message":"Bruteforce attempt from \"46.74.82.159\" detected for action \"login\".","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}
{"reqId":"zcsnWrL3h3nHsA6hu9sZ","level":2,"time":"2019-01-14T09:32:09+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/folder\/list","message":"Login failed: '' (Remote IP: '46.74.82.159')","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}
{"reqId":"zcsnWrL3h3nHsA6hu9sZ","level":1,"time":"2019-01-14T09:32:09+00:00","remoteAddr":"46.74.82.159","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/folder\/list","message":"Bruteforce attempt from \"46.74.82.159\" detected for action \"login\".","userAgent":"okhttp\/3.11.0","version":"14.0.6.0"}`

Maybe there is a problem with the html encoded value @ (%40)?

Best Regards,

David

**Comment by mmalisz** [comment]
@daper, I use v1.10 of the app.
However, I tried to use the token **withouth** OTP enabled.

**Comment by daper** [comment]
Thanks @mmalisz, I misunderstood it, yes. I've could replicate just a couple of times (not consistently). But if it's the error I got, you guys have either a very fast phone or quick nextcloud instance, hehe. Well, I will do the release in the next few days which will include this fix. I would like also to finish some minor things. And you will say please if that fixes this horror issue.

**Comment by mmalisz** [comment]
@daper, thanks. 
Just mention me after the build is ready, so I won't miss it :-)

**Comment by MrFly** [comment]
I think I have the same problem with the current Google Play version of the app. (At least thiels should be related).

I'm using current NC version with external user auth (imap). At this server I'm running fail2ban, so the client get's blocked after failed attempts.

I installed passwords. First try works (the one, where I have to grant access). But then on pulling sites all logins will fail (because of fail2ban - log shows up "wrong password?") - something goes wrong on any further auth attempts. This problem persists only with this password app. I'm running the nextcloud app for file access, which runs fine and should use the same mechanism(?). 

After running Passwords I'm not able to login anymore with my setup from any other app a.s.o., because the client (which is the NC server) is blocked at my mx. 

I have to mention, that my user name is an email address, of course, maybe this is a hint. The NC user therefore has NO password set and no entry in the oc_users table.

**Comment by daper** [comment]
Hi @MrFly, that seems to be the same as @ThePatzen issue. I will have a look too, but as he said it's probably the encoded @ character. Fix on the next release! (hopefully)

**Comment by MrFly** [comment]
@daper thanks a lot. Will try, when it will be available.

**Comment by MrFly** [comment]
@daper diggin further into this I found something else, please have a look. In the logs of my MX I found, that the username was sent was ok - it was the given username. But the password was an other one. It looks like a token:

```
pam(MY_USER_NAME,IP_OF_MY_NC_SERVER) pam_authenticate() failed: Authentication failure (password mismatch?) (given password: QhPn1CKsaYE0j8Q2p6Wr3cObmaIlZtOiwzSiDqb921LfLFMPBkm0GU0tPcRpK0Mf7fE6B6sA)

```

F.Y.I.: This is not my pw :-)

**Comment by daper** [comment]
Thanks @MrFly, that's sad. I will have then to setup a nc instance with IMAP backend to test.

**Comment by MrFly** [comment]
@daper ok. This is very simple. If I can help anyhow, don't hesitate to call.

**Comment by daper** [comment]
An update on this topic. I've already set up a nc instance with imap backend. Have imap php extension installed as well as the `users_external` nextcloud app enabled and added this to `config/config.php`:
```php
'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{imap.gmail.com:993/imap/ssl}',
      ),
    ),
  ),
```
I expect to be able to login with any gmail account on my instance. But I am getting always "Wrong password." error. No error in any log file... I will try to debug it, but if anyone have a hint on how to make it work, would be better.

**Comment by MrFly** [comment]
Better use an other mailservice than google. Because of the two way auth, per-device-passwords and other security options this could be very frustrating to get it to work flawlessly... 

Am 21. Februar 2019 13:15:25 MEZ schrieb daper <notifications@github.com>:
>An update on this topic. I've already set up a nc instance with imap
>backend. Have imap php extension installed as well as the
>`users_external` nextcloud app enabled and added this to
>`config/config.php`:
>```php
>'user_backends' => 
>  array (
>    0 => 
>    array (
>      'class' => 'OC_User_IMAP',
>      'arguments' => 
>      array (
>        0 => '{imap.gmail.com:993/imap/ssl}',
>      ),
>    ),
>  ),
>```
>I expect to be able to login with any gmail account on my instance. But
>I am getting always "Wrong password." error. No error in any log
>file... I will try to debug it, but if anyone have a hint on how to
>make it work, would be better.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/daper/nextcloud-passwords-app/issues/4#issuecomment-465978222

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MrFly** [comment]
@daper Any updates on this? Still does not work on my current setup...

**Comment by ryanprior** [comment]
I can confirm this issue. I just set up my Passwords app, and at first when I logged in using an app password, the "Pulling sites" and "Pulling folders" messages flashed quickly but no accounts were apparently downloaded & I got an empty list. I logged out & then back in using my actual password & TOTP code, which caused the "Pulling sites" message to display for much longer & apparently hang, as it spun nonstop for ~10 minutes. At that point I force-quit the app and started it up again, at which point it downloaded my passwords within ~5 seconds.

**Comment by MrFly** [comment]
Login and pulling seems to work, but I do not get any contents (folders and sites).

**Comment by daper** [comment]
Hi @MrFly, could it be maybe related with #44?

**Comment by daper** [comment]
Hi again @MrFly, I've updated more packages with the very last release and also fixed the #44. Could you test it again? It would be awesome if you tell me that this is finally fixed. Although I don't have many expectations... :/

**Comment by MrFly** [comment]
@daper It works! I can't believe it :-D And it's very fast on loading. Great!!!

**Comment by daper** [comment]
OMG, awesome! cheers :beers: ! Thank you so much for your continuous testing :raised_hands:

**Comment by MrFly** [comment]
Thank you so much for your hard work and finally fixing this :-)
