### ISSUE TITLE
List Empty

### ISSUE THREAD

**Issue by ThePatzen** [daper/nextcloud-passwords-app#42]
Hi!

Login works fine but after pulling sites and folder the list is empty. 

What can I do?
Best Regards!

**Comment by roru69** [comment]
Same problem here. After upgrading to Nextcloud 16.04 and the latest Nextcloud Passwords plugin, the Nextcloud-Passwords app doesn't work anymore. It fails to pull data.

I think that it has something to do with the fact that the Password plugin now seperately asks for a TOTP token. Earlier versions didn't do that.

**Comment by roru69** [comment]
Found the problem. I used the nightly version of the Passwords plugin for Nextcloud. This version triggers the TOTP function in the Passwords plugin for NC. In the stable version of the Passwords plugin the TOTP function isn't triggered and the Android Password App works as expected.

**Comment by Danielsc87** [comment]
Hello. I'm having the same problem. Would you be able to tell me how to install the nightly plug in please I can't find any information cheers. Also do you know if this fixed the same issue with the Web Firefox add on.

**Comment by daper** [comment]
Hi, could you confirm that this is still happening on the latest release v1.12?

**Comment by minibootsmann** [comment]
Just instalked Version 1.12. Login works, but after sync no passwords or folders are shown. The list is empty.
Regards,  Helmut

**Comment by daper** [comment]
Thank you @minibootsmann! Could you please test it again on the very last release (v1.13). I've updated more packages and also fixed few issues more. Maybe this also got fixed... :man_shrugging:

**Comment by daper** [comment]
I am closing this as it looks like it's fixed. But feel free to reopen if needed.

**Comment by minibootsmann** [comment]
> Thank you @minibootsmann! Could you please test it again on the very last release (v1.13). I've updated more packages and also fixed few issues more. Maybe this also got fixed... 🤷‍♂

Even if this case is closed, I would like to answer to this. The App works, everything is eine. Thank you very much for your hard work and enthusiasm!
