### ISSUE TITLE
App stuck on 'pulling sites' 

### ISSUE THREAD

**Issue by ociviol** [daper/nextcloud-passwords-app#47]
I launched the app, connected to my nextcloud and the app displays 'pulling sites' forever...

**Comment by daper** [comment]
Hi @ociviol, could you please confirm that this is still happening on the last release?

**Comment by daper** [comment]
This could be related with #4, which its fix is confirmed now.

**Comment by fuse314** [comment]
I had the same problem after the latest (Android-) app update: I had to re-authenticate, then I was stuck at "pulling sites".
These steps corrected the problem for me:
- go to the app settings for the "Passwords" app (on the phone)
- select "storage"
- delete cache and data (you will lose your current connection(s) in the app)
- start the app and authenticate

I hope this helps you too.

**Comment by daper** [comment]
I am closing the issue. But feel free to reopen if needed.

**Comment by SeverianX** [comment]
Hi. Same problem here,not fixed by wiping cache and data :-(
