### ISSUE TITLE
App should display an error message instead of loading endlesssly in case something goes wrong

### ISSUE THREAD

**Issue by mpodshivalin** [daper/nextcloud-passwords-app#48]
When I enter my own Nextcloud server URL (which by the way has a valid SSL certificate from Let's Encrypt), I get an infinite loading screen:
![20191121_001019](https://user-images.githubusercontent.com/16121630/69279186-e5969c00-0bf4-11ea-9f9f-4979815004fa.jpg)
After that no matter how I restart the app, I still get this throbber. I didn't even get to the entering credentials page. And I can't enter another URL either.
I use this server with Nextcloud app, Notes app, News app, DAVx5, etc, and it worked ok.

It would be a good first step if there was an error message (instead of infinite loading) so I could troubleshoot this problem

**Comment by mirkobrombin** [comment]
Same situation here
