### ISSUE TITLE
freeze nextcloud passwords when users form ispconfig mail

### ISSUE THREAD

**Issue by millosz222** [daper/nextcloud-passwords-app#52]
when users are form ispconfig mail integration (login is mail address) and when i started andorid app and login i cant see any passwords and after that nextcloud passwords (on www) is freeing its loading but really slowly

**Comment by millosz222** [comment]
The loading of app is slowe. 

System Information
Nextcloud Version: 17.0.3
PHP Version: 7.3.11
Passwords Version: 2020.2.1
Browser and Version: Chrome
Client OS and Version: Windows
Server OS and Version: Linux
Steps to reproduce
Click on Passwords link on navbar
Actual result
Passwords load slowly and redirects page twice. During the process the error in the log is generated.

**Comment by millosz222** [comment]
look on the log 
login is milosz.berlik@olsun.pl but your app instead @ does %40
Warning | core | Login failed: 'Milosz.berlik%40olsun.pl' (Remote IP: '192.168.220.99')
-- | -- | --

**Comment by daper** [comment]
Looks like this could be also duplicated of #44
