### ISSUE TITLE
Adjust background for launcher icons

### ISSUE THREAD

**Issue by stefan-niedermann** [daper/nextcloud-passwords-app#53]
Hey @daper,

Nextcloud & Nextcloud Talk changed the background layer of their android app. So i decided to follow with the Notes and Deck app and i provided various Pull Requests for other 3rd party android apps.

Unfortunately i have no idea how you created the pixel graphics for your project.

Can you adapt the new background?

You can find them in this commit (https://github.com/nextcloud/talk-android/pull/695/commits/fb04a7429aeaef4c00e84b8c9f2bb2a7c506be1e) as `.svg` and as an vector drawable `.xml`-file.

Let me know if i can help you in any way :)

**Comment by TessyPowder** [comment]
What exactly is missing ?

I found the logo without the background [here](https://github.com/marius-wieschollek/passwords/blob/master/src/img/app.svg) and the background [here](https://github.com/nextcloud/android/blob/16f7b4e17caec32b4b143d8f8e264958633fe7d0/drawable_resources/icon-background.svg)

**Comment by stefan-niedermann** [comment]
Well, i tried to generate the mipmap via Android Studio, but this function is not available on this project - i guess it has something to do with the circumstate, that this is not a native app but written in javascript 🤷‍♂ 

> and the background here

This was the old background. The official app and the Talk app (and Notes and Deck) are already moving to the new launcher background (see linked PR for Talk).

**Comment by stefan-niedermann** [comment]
Oops, i forgot to link the PR of the Talk app: https://github.com/nextcloud/talk-android/pull/695

**Comment by TessyPowder** [comment]
> This was the old background

Ok. So the new background is [this](https://github.com/nextcloud/talk-android/blob/master/drawable_resources/icon-background.svg)

**Comment by stefan-niedermann** [comment]
Yes :)

**Comment by TessyPowder** [comment]
Is there a reccomended procedure or would this be enough:
https://nextcloud.fractava.com/index.php/s/github-passwords-android-logo/download

**Comment by stefan-niedermann** [comment]
We try to use circular icons. For example

![Deck]( https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/ic_launcher-web.png?raw=true)

But there is no common procedura about shadows or anything, it's just how Android stufio generates the icon.

I will later try ro generate the icons in another project and copy them to this repository, this might work...

**Comment by daper** [comment]
Hi, I will try to tackle it as soon as possible. Thank you all for the
resources and help. And have a happy new year.

**Comment by stefan-niedermann** [comment]
I generated the icons as `.png` and as `.xml` vector drawable. Do you need it as `.svg` as well?

![ic_launcher-web](https://user-images.githubusercontent.com/4741199/71720961-ada18c00-2e23-11ea-93e1-0525cdb1daa7.png)

[password-icons.zip](https://github.com/daper/nextcloud-passwords-app/files/4018910/password-icons.zip)

**Comment by daper** [comment]
With the XML will be enough, as far as i know it can be converted to any
other format without losses, like svg. Thank you again!

**Comment by stefan-niedermann** [comment]
You're welcome :) happy new year, too.

**Comment by daper** [comment]
Released on v1.13.
