### ISSUE TITLE
No passwords

### ISSUE THREAD

**Issue by Danielsc87** [daper/nextcloud-passwords-app#55]
Hello.
Everything logs in no issues. And it won't sync any passwords or folders. I am using nextcloud Version 17. And the latest passwords version 2020. I have 2FA on with Google authentication. When signing in I have to input my credentials and 2FA. I have set the pass code for access the app. On nextcloud activities I can see the app accepts nextcloud password. Any ideas. Cheers.

**Comment by daper** [comment]
Hi @Danielsc87, I've currently tried with TOTP, U2F and the recovery codes for 2FA and all of them works on the latest version of the android app. This should be another thing... Could you please confirm that this is still happening with the latest release?

**Comment by Danielsc87** [comment]
Hi mate

Thanks for the update

I have just reinstalled the app on my phone because it wasnt working and causing lots of errors within the log last version.

But Everything seems to be syncing now and no log errors. I added new passwords from the app and seems to sync both ways. And no issues in the log file.

Nice work, thank you for contacting me and keeping me in the loop I'll keep using it and let you know if any problems.

Thanks again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
