### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by UserXH726** [daper/nextcloud-passwords-app#56]
Without wanting to stress you, is this project still being developed?
I ask because I find it securitycritical for a password app if the last update was over 8 months ago.

Unfortunately I am not a programmer and so I cannot help you.
Are there other ways to support you?

**Comment by CyberneticCody** [comment]
I am wondering the same, I don't see much activity here, and I am having some trouble with the app as well... Would be great if this project kept going!
Unfortunately because the app has not been updated we came to the conclusion that we can not keep it enabled due to security concerns.

**Comment by daper** [comment]
I've been off for a while. But just did a release! check it out :)

Answer issues here, provide replication steps for those that doesn't have or identify duplicates are also other good ways to help out here. :+1: 

@CyberneticCody I hope you find interest again for the app with the updated release.
