### ISSUE TITLE
Support self signed cert

### ISSUE THREAD

**Issue by D1Ck3n** [daper/nextcloud-passwords-app#59]
Hi,

as i read in [#12](https://github.com/daper/nextcloud-passwords-app/issues/12), the app does not support self signed certificates. Probably that's why I always get "Network Error" when I use the Android app. Is it possible to add an option "allow self signed certificates"?

Greetings

**Comment by daper** [comment]
Hi, there is no option to allow self-signed certificates. But you should be able to add your own CA and login with a certificate signed by it or its trust chain. Thank you!

**Comment by daper** [comment]
I am closing this, but feel free to reopen if needed.
