### ISSUE TITLE
App automatically uppercases https and fails

### ISSUE THREAD

**Issue by CyberneticCody** [daper/nextcloud-passwords-app#60]
When opening the app for the first time, the text box automatically uppercase https to Https and causes a network error. The error is nondescript so that is all the information I have.
Android 10, latest app version from Google Play

**Comment by daper** [comment]
Hi @CyberneticCody, as described in the issue #2, the scheme part of the url is not necessary. So it can be omitted. I am going to close this issue as this seems more a error feedback/logging issue. Thank you anyways for raising it.
