### ISSUE TITLE
Initialize custom fields when creating new password entry

### ISSUE THREAD

**Issue by benginoe** [daper/nextcloud-passwords-app#62]
Initialize custom fields when creating new password, otherwise custom fields can't be added in the webapp.

In relation to the issue here (https://github.com/marius-wieschollek/passwords/issues/243#issuecomment-587182167), there is a bug in the app, as it doesn't initialize the custom fields array which occurs an error in the webapp. 

App version is 1.11 
OS: android 10

Would appreciate a fix for this. Thank you for your great work so far!

**Comment by daper** [comment]
This should be fixed on the latest release. Feel free to reopen if needed.
