### ISSUE TITLE
no release on f-droid

### ISSUE THREAD

**Issue by thrillfall** [daper/nextcloud-passwords-app#65]
The release with the login fix (https://github.com/daper/nextcloud-passwords-app/releases/tag/v1.14) is now roughly 6 days old and yet no new release has appeared in the f-droid repo? Is there someway we can follow the progress on the f-droid build?

**Comment by daper** [comment]
Hi @thrillfall, the build is failing on fdroid. I have to debug and solve the issues... I opened a MR but I've just close, as there are some errors on the compilation. Any helping hand is also welcomed :) For the moment I think you can use the APK that I upload here to each release.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6453

**Comment by thrillfall** [comment]
i don't see any link to apk?

**Comment by daper** [comment]
If you go here to the [releases page](https://github.com/daper/nextcloud-passwords-app/releases). You will find under "assets" the apk.
![ksnip_20200312-115324](https://user-images.githubusercontent.com/5327718/76514577-65709c80-6458-11ea-9e25-5ede7676d776.png)

**Comment by thrillfall** [comment]
sorry, i was to dumb to find this page. thank you!

**Comment by stefan-niedermann** [comment]
Well that's no solution for F-Droid users.

@daper if you need help regarding F-Droid specific stuff, you might want to ping "BuBu" - which is always helping me with this kind of stuff (didn't directly ping him because i am not sure whether the problems are on F-Droid or on your side 😉 )

**Comment by daper** [comment]
Hi! I am waiting for this merge to close. I think it will fix the issue: https://gitlab.com/fdroid/fdroidserver/-/merge_requests/771

**Comment by daper** [comment]
I've made another MR to build it successfully on f-droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7325
