### ISSUE TITLE
Upgrade icon

### ISSUE THREAD

**Issue by PanderMusubi** [daper/nextcloud-passwords-app#68]
Please upgrade icon to use the latest Nextcloud style as seen in

The [current icon]https://f-droid.org/en/packages/com.nextcloudpasswords/) is using an old style.

![](https://f-droid.org/repo/it.niedermann.owncloud.notes/en-US/icon_sOQTkc5JR-7Dt0WXW7WjbRHJGMYqqVVBTfhCJ9fjQhA=.png)

![](https://f-droid.org/repo/net.eneiluj.nextcloud.phonetrack/en-US/icon_2Y3hr_vJTBENNf8nIzwDWW8obMWeYKCMKnulOpWeYkg=.png)

![](https://f-droid.org/repo/icons-640/org.schabi.nxbookmarks.6.png)

![](https://f-droid.org/repo/icons-640/fr.unix_experience.owncloud_sms.69.png)

**Comment by TessyPowder** [comment]
The one on F-Droid uses the new design and the other examples use the old style.

**Comment by TessyPowder** [comment]
![](https://user-images.githubusercontent.com/4741199/71670475-3a8b0d80-2d70-11ea-839c-8707fdf0dd8e.png)
left side: old
right side: new

**Comment by stefan-niedermann** [comment]
@PanderMusubi : @TessyPowder is right. The gradient is the new icon, the bubbled one is outdated. Therefore everything right so far.

But the Play Store icon is still outdated. @daper let me know if i should generate the icon again or so 🙂

**Comment by daper** [comment]
Closing as it's released, but feel free to reopen if needed.
