### ISSUE TITLE
doesn't connect anymore

### ISSUE THREAD

**Issue by torebrigaglia** [daper/nextcloud-passwords-app#69]
Hi
Since last update of nextclod, the app remains loading forever.
It authenticates correctly but does not load the sites.
All good on the nextcloud side, where i can operate it normally.

**Comment by daper** [comment]
Hi, could you clear app data or reinstall the app and see if it still happens?

**Comment by torebrigaglia** [comment]
Sure. I'll do that now.

Il Mer 1 Apr 2020, 12:58 David Peralta <notifications@github.com> ha
scritto:

**Comment by torebrigaglia** [comment]
Cleared data did the trick! Thanks.

Il Mer 1 Apr 2020, 12:58 David Peralta <notifications@github.com> ha
scritto:

**Comment by daper** [comment]
Great! This was quick :) closing...

**Comment by amanajayvarma** [comment]
I am using Passman in NextCloud and the solution doesn't work for me.

**Comment by daper** [comment]
Hi @amanajayvarma, this app works with Nextcloud Passwords, not Passman.

**Comment by amanajayvarma** [comment]
Ok : (
