### ISSUE TITLE
App keeps updating from Play Store

### ISSUE THREAD

**Issue by joostvkempen** [daper/nextcloud-passwords-app#7]
When installed, Google Play store keeps saying 'update available'. A few seconds after updating, it's again 'update available'. Removed and reinstalled the app, still the same problem.  App-version 1.7, Android 7.0 on Samsung Galaxy A3 (2016).

**Comment by daper** [comment]
Hi @joostvkempen, that seems a Google Play issue and strange behavior indeed. Releases are done at the same time here on Github and Google Play. The only difference is that Google signs the app when uploading to their market.

**Comment by joostvkempen** [comment]
It looks like Google Play thinks the version number of the installed app is lower than the version number in the store. Could there be an older number left behind in some config file?

**Comment by joostvkempen** [comment]
Strange, I'll just have to wait for the next release then...

**Comment by daper** [comment]
Hi @joostvkempen, people on the Play Store answered. They’ve recently made some changes that should fix the problem. Please check to see if you’re still experiencing the same issue.

**Comment by joostvkempen** [comment]
Tnx! Problem solved!
