### ISSUE TITLE
Website/address field is not clickable

### ISSUE THREAD

**Issue by lbdroid** [daper/nextcloud-passwords-app#73]
When creating a password, either from within this, or through a web browser, if you enter a website address, it is not (in this program) clickable. In the nextcloud website, it is clickable. Note that adding a custom field with type set to "link" is presented in this program as a clickable link.

The website/address field should be clickable to open the url in a web browser.

**Comment by daper** [comment]
Closing as it's released, but feel free to reopen if anything is not right. :)
