### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by redisded** [daper/nextcloud-passwords-app#8]
Hi,

I would love to try your app, but it keeps telling me "Network error" while I try to connect, whitout any other information.
I'm logged in my nextcloud instance on the phone while I'm trying, and can access to the password app.

I tried several ways to set my instance address : 

https://mydomain.fr/nextcloud (with or without slash)
mydomain.fr/nextcloud (with or without slash)
I tried to add the path to the password app with no more success.

My Nextcloud logs don't show any error.

How could I troubleshot the problem ?

Thank in advance.

Redisded.

**Comment by redisded** [comment]
After trying another app, I have the same problem, with more info : java.security.cert.CertPathValidatorException : Trust anchor for certification path not found

It seems to be related to my letsencrypt certificate.

Do you had known issues with letsencrypt certificate ?

**Comment by daper** [comment]
Hi @redisded, I was trying to figure out what could be the problem... If the certificate is still valid and signed by LetsEncrypt it shouldn't be a problem. On my instance I have it running without issues and using LetsEncrypt even with a private IP. Ensure you are serving the proper certificate on your http server.

**Comment by redisded** [comment]
I forgot to say that my certificate is accepted with my browser without warning.

However, I've tested it on sslshopper.com and had this warning : 


  | The  certificate is not trusted in all web browsers. You may need to install  an Intermediate/chain certificate to link it to a trusted root  certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.
-- | --

Not sure if this is the problem, do you have the same warning with yours ?

I've just tried a similar app to sync my bookmarks an get a "network error" too, without any information so I'm starting to think there's a problem with my certificate but can't see what...

I don't want to give more information on my domain, but would you agree if I send you a mail with my domain name so you can check if you see something wrong with my certificate on the contact mail you give on the android app page ?
I would agree to create a temp account if you wish.

I really have a great interest in your app so many thanks for you help !

**Comment by redisded** [comment]
I must add that my nextcloud instance is behind  a reverse proxy (haproxy). Haproxy is managing the cert. May it be a cause of the problem?

Le 5 décembre 2018 15:41:31 GMT+01:00, daper <notifications@github.com> a écrit :
>Hi @redisded, I was trying to figure out what could be the problem...
>If the certificate is still valid and signed by LetsEncrypt it
>shouldn't be a problem. On my instance I have it running without issues
>and using LetsEncrypt even with a private IP. Ensure you are serving
>the proper certificate on your http server.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/daper/nextcloud-passwords-app/issues/8#issuecomment-444508284

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by daper** [comment]
Hi @redisded, yes. You can write me on email if you wish. But better to log here for anyone with the same problem in the future. The only explanation I find on your problem is that you are using just the single certificate and not the "full-chain". Have you checked that?

**Comment by redisded** [comment]
That's exactly what I was correcting right now ;-)

That was the problem, sorry for my mistakes, and thank you for your help 
!



Le 2018-12-05 16:30, daper a écrit :

**Comment by daper** [comment]
Cool! Closing then.
