### ISSUE TITLE
Sort Passwords / Multiple Accounts

### ISSUE THREAD

**Issue by impius-ch** [daper/nextcloud-passwords-app#83]
Hi there
It would be awsome if we can sort the passworsds by name in the android app.
Also it would be great if we can connect the password app to multiple sites or/and accounts.
But anyway, thanks for a great password manager! 

Cheers

**Comment by daper** [comment]
Hi! I am glad you appreciate it and thank you for installing! This issue is duplicated of #36 and #79. I am closing it but feel free to reopen if needed.
