### ISSUE TITLE
fdroid version is very old? 1.11

### ISSUE THREAD

**Issue by Emporea** [daper/nextcloud-passwords-app#84]
Hey. 

F Droid only shows me the version 1.11 from 15/05/2019. 
I am on Android 10.

In #65 you are obviously discussing about newer releases so what am I doing wrong?

**Comment by daper** [comment]
Hello @Emporea, we are following the progress in #65. Right now everything is pending of a MR on the fdroiddata repo in gitlab. I am closing this issue, but feel free to reopen if needed
