### ISSUE TITLE
Security Enhancement

### ISSUE THREAD

**Issue by redisded** [daper/nextcloud-passwords-app#9]
Hi,

Thanks again for your app, but I believe letting all the passwords available on my phone without security when you open the application is pretty dangerous !

Would it be possible to ask for a master password when you open the app, or, even better, user the fingerprint reader, as many app does ?

Thanks in advance.

Best regards.

Redisded.

**Comment by daper** [comment]
Hi, this is the next feature on my list. It will be available soon.

**Comment by redisded** [comment]
Great !

Thanks again

Le 6 décembre 2018 23:30:01 GMT+01:00, daper <notifications@github.com> a écrit :
>Hi, this is the next feature on my list. It will be available soon.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/daper/nextcloud-passwords-app/issues/9#issuecomment-445053558

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by roru69** [comment]
Hi!

Exactly my question. I'm using the Android Password App in combination with Nextcloud 15 RC3 without any problems. A master password/Fingerprint authentication to enhance security would be highly appreciated.

Regards, Roru69

**Comment by daper** [comment]
Hi @redisded, @roru69. Feature released. Check it out on v1.8.
